"""Every model in one package, so Alembic sees the whole schema at once.

Import order matters only in that `Base.metadata` must be fully populated
before a migration is autogenerated.
"""
from app.models.base import BilingualMixin, TimestampMixin, new_id, uuid_fk, uuid_pk
from app.models.catalog import Category, Product, ProductMedia, ProductStatus
from app.models.notify import Notification
from app.models.orders import (
    ALLOWED_TRANSITIONS,
    TERMINAL_STATUSES,
    Order,
    OrderEvent,
    OrderItem,
    OrderStatus,
)
from app.models.user import RefreshToken, User, UserRole

__all__ = [
    "ALLOWED_TRANSITIONS",
    "TERMINAL_STATUSES",
    "BilingualMixin",
    "Category",
    "Notification",
    "Order",
    "OrderEvent",
    "OrderItem",
    "OrderStatus",
    "Product",
    "ProductMedia",
    "ProductStatus",
    "RefreshToken",
    "TimestampMixin",
    "User",
    "UserRole",
    "new_id",
    "uuid_fk",
    "uuid_pk",
]
