"""custom requests

Revision ID: 384763118191
Revises: 435e72dddecd
Create Date: 2026-08-06 07:52:47.370063
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = '384763118191'
down_revision: str | None = '435e72dddecd'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('custom_requests',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('reference', sa.String(length=12), nullable=False),
    sa.Column('tracking_token', sa.String(length=64), nullable=False),
    sa.Column('customer_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('customer_name', sa.String(length=255), nullable=False),
    sa.Column('customer_phone', sa.String(length=30), nullable=False),
    sa.Column('customer_email', sa.String(length=255), nullable=True),
    sa.Column('lang', sa.String(length=2), nullable=False),
    sa.Column('city', sa.String(length=120), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('budget', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('references', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('source', sa.String(length=40), nullable=False),
    sa.Column('product_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('status', sa.Enum('requested', 'quoted', 'approved', 'in_production', 'ready', 'delivered', 'declined', 'withdrawn', name='request_status'), nullable=False),
    sa.Column('quote_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('quote_note_en', sa.Text(), nullable=False),
    sa.Column('quote_note_ar', sa.Text(), nullable=False),
    sa.Column('lead_time_days', sa.Integer(), nullable=True),
    sa.Column('promised_for', sa.Date(), nullable=True),
    sa.Column('order_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_custom_requests_created_at'), 'custom_requests', ['created_at'], unique=False)
    op.create_index(op.f('ix_custom_requests_customer_id'), 'custom_requests', ['customer_id'], unique=False)
    op.create_index(op.f('ix_custom_requests_customer_phone'), 'custom_requests', ['customer_phone'], unique=False)
    op.create_index(op.f('ix_custom_requests_reference'), 'custom_requests', ['reference'], unique=True)
    op.create_index(op.f('ix_custom_requests_status'), 'custom_requests', ['status'], unique=False)
    op.create_index(op.f('ix_custom_requests_tracking_token'), 'custom_requests', ['tracking_token'], unique=True)
    op.create_table('request_events',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('request_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('status', sa.Enum('requested', 'quoted', 'approved', 'in_production', 'ready', 'delivered', 'declined', 'withdrawn', name='request_status'), nullable=False),
    sa.Column('actor', sa.String(length=30), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['request_id'], ['custom_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_request_events_created_at'), 'request_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_request_events_request_id'), 'request_events', ['request_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_request_events_request_id'), table_name='request_events')
    op.drop_index(op.f('ix_request_events_created_at'), table_name='request_events')
    op.drop_table('request_events')
    op.drop_index(op.f('ix_custom_requests_tracking_token'), table_name='custom_requests')
    op.drop_index(op.f('ix_custom_requests_status'), table_name='custom_requests')
    op.drop_index(op.f('ix_custom_requests_reference'), table_name='custom_requests')
    op.drop_index(op.f('ix_custom_requests_customer_phone'), table_name='custom_requests')
    op.drop_index(op.f('ix_custom_requests_customer_id'), table_name='custom_requests')
    op.drop_index(op.f('ix_custom_requests_created_at'), table_name='custom_requests')
    op.drop_table('custom_requests')
    # ### end Alembic commands ###
