"""feed weights

Revision ID: 435e72dddecd
Revises: 8a049e80b37e
Create Date: 2026-08-06 07:43:56.650874
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = '435e72dddecd'
down_revision: str | None = '8a049e80b37e'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feed_weights',
    sa.Column('key', sa.String(length=40), nullable=False),
    sa.Column('value', sa.Numeric(precision=6, scale=3), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('feed_weights')
    # ### end Alembic commands ###
