"""piece alerts

Revision ID: 1c57fa6ff86d
Revises: 384763118191
Create Date: 2026-08-06 14:26:34.419853
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = '1c57fa6ff86d'
down_revision: str | None = '384763118191'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('piece_alerts',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('product_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('lang', sa.String(length=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('notified_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', 'phone', name='uq_alert_product_phone')
    )
    op.create_index('ix_alerts_pending', 'piece_alerts', ['product_id', 'notified_at'], unique=False)
    op.create_index(op.f('ix_piece_alerts_created_at'), 'piece_alerts', ['created_at'], unique=False)
    op.create_index(op.f('ix_piece_alerts_phone'), 'piece_alerts', ['phone'], unique=False)
    op.create_index(op.f('ix_piece_alerts_product_id'), 'piece_alerts', ['product_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_piece_alerts_product_id'), table_name='piece_alerts')
    op.drop_index(op.f('ix_piece_alerts_phone'), table_name='piece_alerts')
    op.drop_index(op.f('ix_piece_alerts_created_at'), table_name='piece_alerts')
    op.drop_index('ix_alerts_pending', table_name='piece_alerts')
    op.drop_table('piece_alerts')
    # ### end Alembic commands ###
